name: CI/CD to Render

on:
  push:
    branches: [ "main" ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run tests
        run: python -c "from app import app; print('App Imported Successful')"

  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest
    needs: test-python
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context:
          push: true
          tags: |
            ghcr.io/${{github.repository_owner}}/my-python-app:latest
            ghcr.io/${{github.repository_owner}}/my-python-app:${{github.sha}}
    
    deployer:
      name: Deploy to Render
      runs-on: ubuntu-latest
      need: build-and-push
      if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Render
        run: |
          curl -s -x POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
          -H "Content-Type: application/json" \
          "https://api.render.com/vl/service/${{ secrets.RENDER_SERVICE_ID }}\deploys"
          echo "Deployment triggered to: "
          echo "https://${{ secrets.RENDER_SERVICE_ID }}.onrender.com"    